ConfigSchedulePlatform:
DEFAULT_HIGHT = 0
DEFAULT_LOWEST = 1
PC = 2
PS4_HIGH = 3
PS4_LOW = 4
SWITCH = 5
IOS_HIGH = 6
IOS_MEDIUM = 7
IOS_LOW = 8
ANDROID_HIGH = 9
ANDROID_MEDIUM = 10
ANDROID_LOW = 11

ConfigScheduleJobType:
Default = 0
LOSE = 1

ConfigSchedulerType:
I_UPDATE = 0
I_LATE_PRE_UPDATE = 1
I_LATE_POST_UPDATE = 2
I_AFTER_RES_TO_UPDATE_END = 3
I_LATE_POST_UPDATE_TO_NEXT_BEFORE_LATE_UPDATE = 4
I_RENDER_TO_NEXT_BEFORE_RES = 5
I_RENDER_TO_NEXT_BEFORE_LATE_UPDATE = 6
G_RENDER_TO_NEXT_BEFORE_LATE_UPDATE = 100

