PlayMode:
PLAY_MODE_ALL = 0
PLAY_MODE_SINGLE = 1
PLAY_MODE_MULTIPLE = 2

LogicType:
LOGIC_NONE = 0
LOGIC_AND = 1
LOGIC_OR = 2
LOGIC_NOT = 3
LOGIC_A_AND_ETCOR = 4
LOGIC_A_AND_B_AND_ETCOR = 5
LOGIC_A_OR_ETCAND = 6
LOGIC_A_OR_B_OR_ETCAND = 7
LOGIC_A_AND_B_OR_ETCAND = 8

BanGroupType:
BAN_GROUP_INVALID = 0
BAN_GROUP_COMMON = 1
BAN_GROUP_TRANSPORT_ONLY = 2
BAN_GROUP_TRANSPORT_MAP = 3
BAN_GROUP_TRANSPOR_GOTO_SCENE = 4

BanType:
BAN_INVALID = 0
BAN_TRANSPORT = 1
BAN_GOTO_SCENE = 2
BAN_NPC_INTERACTION = 3
BAN_GOTO_MULTIPLAYER = 4