GuideOpenStateType:
OPEN_STATE_NONE = 0
OPEN_STATE_PAIMON = 1
OPEN_STATE_PAIMON_NAVIGATION = 2
OPEN_STATE_AVATAR_PROMOTE = 3
OPEN_STATE_AVATAR_TALENT = 4
OPEN_STATE_WEAPON_PROMOTE = 5
OPEN_STATE_WEAPON_AWAKEN = 6
OPEN_STATE_QUEST_REMIND = 7
OPEN_STATE_GAME_GUIDE = 8
OPEN_STATE_COOK = 9
OPEN_STATE_WEAPON_UPGRADE = 10
OPEN_STATE_RELIQUARY_UPGRADE = 11
OPEN_STATE_RELIQUARY_PROMOTE = 12
OPEN_STATE_WEAPON_PROMOTE_GUIDE = 13
OPEN_STATE_WEAPON_CHANGE_GUIDE = 14
OPEN_STATE_PLAYER_LVUP_GUIDE = 15
OPEN_STATE_FRESHMAN_GUIDE = 16
OPEN_STATE_SKIP_FRESHMAN_GUIDE = 17
OPEN_STATE_GUIDE_MOVE_CAMERA = 18
OPEN_STATE_GUIDE_SCALE_CAMERA = 19
OPEN_STATE_GUIDE_KEYBOARD = 20
OPEN_STATE_GUIDE_MOVE = 21
OPEN_STATE_GUIDE_JUMP = 22
OPEN_STATE_GUIDE_SPRINT = 23
OPEN_STATE_GUIDE_MAP = 24
OPEN_STATE_GUIDE_ATTACK = 25
OPEN_STATE_GUIDE_FLY = 26
OPEN_STATE_GUIDE_TALENT = 27
OPEN_STATE_GUIDE_RELIC = 28
OPEN_STATE_GUIDE_RELIC_PROM = 29
OPEN_STATE_COMBINE = 30
OPEN_STATE_GACHA = 31
OPEN_STATE_GUIDE_GACHA = 32
OPEN_STATE_GUIDE_TEAM = 33
OPEN_STATE_GUIDE_PROUD = 34
OPEN_STATE_GUIDE_AVATAR_PROMOTE = 35
OPEN_STATE_GUIDE_ADVENTURE_CARD = 36
OPEN_STATE_FORGE = 37
OPEN_STATE_GUIDE_BAG = 38
OPEN_STATE_GUIDE_ADVENTURE_DAILYTASK = 40
OPEN_STATE_GUIDE_ADVENTURE_DUNGEON = 41
OPEN_STATE_SHOP_TYPE_PAIMON = 1001
OPEN_STATE_SHOP_TYPE_CITY = 1002
OPEN_STATE_SHOP_TYPE_BLACKSMITH = 1003
OPEN_STATE_SHOP_TYPE_GROCERY = 1004
OPEN_STATE_SHOP_TYPE_FOOD = 1005

GuidePageType:
Normal = 0
EquipPromote = 1
RelicPromote = 2
TalentInfo = 3
RelicInfo = 4
WeaponInfo = 5
SkillInfo = 6

GuideAvatarState:
Normal = 0
Move = 1
CanFly = 2
Fly = 3
TryToMove = 4
CanPromote = 5
CanUpGrade = 6

GuideButtonClick:
Click = 0
PressDown = 1
Charge = 2
Toggle = 3

GuideItemType:
Normal = 0
Weapon = 1
Relic = 2
Any = 3

GuideCameraAction:
Move = 0
Scale = 1

GuideAvatarAction:
Move = 0
Attack = 1

GuideHasAvatarType:
Normal = 0
InTeam = 1

GuideHasAvatarConType:
ID = 0
Level = 1

GuidePlatform:
None = 0
iOS = 1
Standalone = 2
Android = 3
PS4 = 4
Switch = 5

GuideLevelType:
All = 0
NotDungeon = 1
OnlyBigWorld = 2

GuideKeyClick:
PressDown = 0
Click = 1
Charge = 2

ButtonGuideType:
Normal = 0
Red = 1
Blink = 2

MaskGuideType:
Normal = 0
Black = 1

WidgetInfoPos:
TL = 0
T = 1
TR = 2
L = 3
R = 4
BL = 5
B = 6
BR = 7

GuideWidgetSpecialType:
Normal = 0
Slot = 1
CharacterAvatarBtn = 2
CharacterFuncBtn = 3
CharacterAvatarBtnByLevel = 4