DropRandomType:
DROP_RANDOM_BY_WEIGHT = 0
DROP_RANDOM_INDEPENDENT = 1

DropNodeType:
DROP_NODE_LEAF = 0
DROP_NODE_TREE = 1

DataEntityType:
DATA_ENTITY_NONE = 0
DATA_ENTITY_MONSTER = 1
DATA_ENTITY_GADGET = 2